apiVersion: v1
kind: Service
metadata:
  name: lava1
  labels:
    app.kubernetes.io/name: lava1
    app.kubernetes.io/instance: lava1
spec:
  ports:
    - port: 8081
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: lava1
    app.kubernetes.io/instance: lava1
